name: Backend CI

on:
  push:
    branches:
      - main
      - dockerSetup
  pull_request:
    branches:
      - main
      - dockerSetup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t backend-ci-test .

      # (Optional) If you have tests, add a step to run them here, for example:
      # - name: Run tests
      #   run: docker run backend-ci-test npm test
