name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dockerSetup
  pull_request:
    branches:
      - main
      - dockerSetup

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run tests with Maven
        run: ./mvnw test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t backend-ci-test .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dockerSetup'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy backend repo to VM via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "."
          target: "~/Business-Connect/Business-Connect-Backend"
          rm: false

      - name: Run Docker Compose on VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~/Business-Connect
            docker compose up -d --build backend
